apps/products/urls.py
from django.urls import path

from . import views

app_name = "products"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.UpdateProductView.as_view(), name="update"),
    path("create/", views.CreateProductView.as_view(), name="create"),
    path("<int:pk>/delete/", views.DeleteProductView.as_view(), name="delete"),
]

coffeepy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('products/', include('apps.products.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/customers/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Customer(models.Model):
    """Customer information."""

    name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    tax_id = models.TextField(blank=True, default="C/F")
    address = models.TextField(blank=True, default="Ciudad")
    phone = PhoneNumberField(blank=True)
    email = models.EmailField(blank=True)

    def __str__(self):
        return self.name + " " + self.last_name

apps/orders/models.py
from django.db import models
from ..products.models import Product
from ..customers.models import Customer
from django.db.models.signals import pre_save, post_save, post_delete


class Invoice(models.Model):
    """Model definition for Invoice."""

    # TODO: return customer name from order

    PAYMENT_CHOICES = [
        ("cs", "cash"),
        ("ca", "card"),
        ("cu", "cupon"),
    ]
    invoice_number = models.CharField(max_length=12)
    date = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    order = models.OneToOneField("Order", on_delete=models.CASCADE)
    payment = models.CharField(max_length=2, choices=PAYMENT_CHOICES)

    def __str__(self):
        return str(self.order.id)
    
    def total(self):
        return self.order.total

def invoice_post_save_receiver(sender, instance, *args, **kwargs):
    """Calls update_status def from Order Model"""
    instance.order.update_status("pa")

post_save.connect(invoice_post_save_receiver, sender=Invoice)

class Order(models.Model):
    """Customer orders and state management."""

    # TODO: delivery_type: To eat here or carry out

    STATUS_CHOICES = [
        ("re", "received"),
        ("pa", "payed"),
        ("co", "cooking"),
        ("rd", "ready"),
        ("de", "delivered"),
    ]
    date = models.DateTimeField(auto_now_add=True)
    product = models.ManyToManyField(Product, through="OrderDetail")
    status = models.CharField(max_length=4, choices=STATUS_CHOICES, default="re")
    total = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)

    def update_total(self):
        total = 0
        products = self.orderdetail_set.all()
        for product in products:
            total += product.subtotal
        self.total = total
        self.save()

    def update_status(self, choice):
        self.status = choice
        self.save()

    def __str__(self):
        return str(self.id)


class OrderDetail(models.Model):
    """Order detail as quantity of each product and price."""

    order = models.ForeignKey(Order, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    subtotal = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)

    def remove(self):
        return self.product.remove_from_order()

    def __str__(self):
        return self.product.name


def order_product_pre_save_receiver(sender, instance, *args, **kwargs):
    """Pre saves the price and subtotal of orders."""
    qty = instance.quantity
    if qty >= 1:
        price = instance.product.price
        subtotal = qty * price
        instance.price = price
        instance.subtotal = subtotal


pre_save.connect(order_product_pre_save_receiver, sender=OrderDetail)

def order_product_post_save_receiver(sender, instance, *args, **kwargs):
    """Calls update_total def from Order Model"""
    instance.order.update_total()

post_save.connect(order_product_post_save_receiver, sender=OrderDetail)

post_delete.connect(order_product_post_save_receiver, sender=OrderDetail)

apps/products/models.py
from django.db import models

class ProductType(models.Model):
    """Defines product types like breakfast, salads, meals or beverages."""

    name = models.CharField(max_length=60)
    description = models.TextField()
    start_hour = models.TimeField()
    end_hour = models.TimeField()

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    """Defines ingredients for products."""

    UNIT_CHOICES = [
        ("L", "litres"),
        ("lb", "pound"),
        ("mL", "mililitres"),
        ("g", "grams"),
        ("gal", "gallon"),
        ("kg", "kilograms"),
        ("oz", "ounces"),
        ("unit", "unit"),
    ]
    name = models.CharField(max_length=60)
    cost = models.DecimalField(max_digits=6, decimal_places=2)
    expiration_date = models.DateField()
    stock = models.IntegerField()
    unit_quantity = models.DecimalField(max_digits=6, decimal_places=2)
    unit = models.CharField(max_length=4, choices=UNIT_CHOICES)

    def __str__(self):
        return self.name + " " + str(self.unit_quantity) + " " + self.unit


class Product(models.Model):
    """Defines products for sale."""

    image = models.ImageField(upload_to="products")
    product_type = models.ForeignKey(ProductType, on_delete = models.PROTECT)
    name = models.CharField(max_length=60)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    ingredients = models.ManyToManyField(Ingredient, through="Recipe")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return u'/products/%d' % self.id 


class Recipe(models.Model):
    """Defines how much ingredients needs each product."""

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    unit_quantity = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.product.name

apps/customers/views.py
from django.shortcuts import render

# Create your views here.

apps/orders/views.py
from django.shortcuts import render

# Create your views here.

apps/products/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory

from .models import Product, Recipe

class IndexView(generic.ListView):
    model = Product
    template_name = "products/index.html"


class DetailView(generic.DetailView):
    model = Product
    template_name = "products/detail.html"

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context["ingredients"] = Recipe.objects.filter(product=self.object)
        return context

class IngredientInLine(InlineFormSetFactory):
    model = Recipe
    fields = '__all__'

class UpdateProductView(UpdateWithInlinesView):
    model = Product
    inlines = [IngredientInLine]
    fields = ['image','product_type','name', 'description', 'price']
    template_name = 'products/form.html'

class CreateProductView(CreateWithInlinesView):
    model = Product
    inlines = [IngredientInLine]
    fields = ['image','product_type','name', 'description', 'price']
    template_name = 'products/form.html'

class DeleteProductView(generic.DeleteView):
    model = Product
    template_name = 'products/delete.html'
    success_url = reverse_lazy('products:index')

templates/base.html
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Coffee Py </title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% load staticfiles %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
            <img src="{% static 'logo.svg' %}" height="42" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'products:index' %}">Products <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Orders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Customers</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>

</html>

templates/products/delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

templates/products/detail.html
<h1>{{ product }} - Q. {{ product.price }}</h1>
<p>{{ product.product_type }}</p>
<img src="{{ product.image.url }}" style="max-width: 200px">
<p>{{ product.description }}</p>
<h3>Ingredientes</h3>

<ul>
    {% for recipe in ingredients %}
        <li>{{ recipe.ingredient.name }} - {{ recipe.unit_quantity }} {{ recipe.ingredient.unit }}</li>
    {% endfor %}
</ul>

<a href="{% url 'products:delete' product.id %}"> delete<a/>

templates/products/form.html
{% extends 'base.html' %}

{% block content %}

{% load bootstrap4 %}
{% load widget_tweaks %}

<h1>Products</h1>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
  {% bootstrap_form form layout='inline' %}
  <h3>Ingredients</h3>
  {% for formset in inlines %}
  {% for form in formset %}
  <div class="form-group row">
    {% for field in form.visible_fields %}
    <div class="col">{{ field.label }} {{ field | add_class:"form-control" }}</div>
    {% endfor %}
  </div>
  {% endfor %}
  {% endfor %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
</form>
{% endblock %}

templates/products/index.html
<a href="{% url 'products:create' %}"> create </a>
<ul>
    {% for product in object_list %}
        <img src="{{ product.image.url }}" style="max-height: 100px; padding: 10px;">
        <li><a href="{% url 'products:detail' product.id %}">{{ product.name }}</a> <a href="{% url 'products:update' product.id %}"> update<a/></li>
    {% empty %}
        <li>No products yet.</li>
    {% endfor %}
</ul>